//
//  CameraDelegate.swift
//  AIKit (Generated by SwiftyLaunch 1.5.0)
//  https://docs.swiftylaun.ch/module/aikit/ai-vision-example
//

import AVFoundation
import AnalyticsKit
import SwiftUI

// The View Name for Analytics Capture
private let viewName = "CameraDelegate"

/// Delegate to receive events from the camera
class CameraDelegate: NSObject, AVCapturePhotoCaptureDelegate {

	private let completion: (UIImage?) -> Void

	init(completion: @escaping (UIImage?) -> Void) {
		self.completion = completion
	}

	func photoOutput(_ output: AVCapturePhotoOutput, didFinishProcessingPhoto photo: AVCapturePhoto, error: Error?) {
		if let error {
			print("[CAMERA DELEGATE]: Error while capturing photo: \(error)")
			Analytics.capture(
				.error, id: "photo_output", longDescription: "Error: \(error.localizedDescription)",
				source: .aikit, fromView: viewName)
			completion(nil)
			return
		}

		if let imageData = photo.fileDataRepresentation(), let capturedImage = UIImage(data: imageData) {
			print("[CAMERA DELEGATE]: Captured Image")
			completion(capturedImage)
		} else {
			print("[CAMERA DELEGATE]: Error: Image not fetched")
			Analytics.capture(
				.error, id: "photo_output", longDescription: "Error: Image not fetched", source: .aikit,
				fromView: viewName)

		}
	}
}
